module Data exposing (data)

import Dict exposing (Dict)


data : Dict Int ( String, String )
data =
    Dict.fromList
        [ ( 1, ( "Abate", "To decrease; reduce" ) )
        , ( 2, ( "Abdicate", "To give up a position, right, or power" ) )
        , ( 3, ( "Aberrant", "Deviating from what is normal" ) )
        , ( 4, ( "Abeyance", "A temporary suppression or suspension" ) )
        , ( 5, ( "Abject", "Miserable; pitiful" ) )
        , ( 6, ( "Abjure", "To reject; abandon formally" ) )
        , ( 7, ( "Abscission", "The act of cutting; the natural seperation of a leaf or other part of a plant" ) )
        , ( 8, ( "Abscond", "To depart secretly" ) )
        , ( 9, ( "Abstemious", "Moderate in appetite" ) )
        , ( 10, ( "Abstinence", "The giving up of certain pleasures" ) )
        , ( 11, ( "Abysmal", "Very bad" ) )
        , ( 12, ( "Accretion", "Growth in size or increase in amount" ) )
        , ( 13, ( "Accrue", "To accumulate; grow by additions" ) )
        , ( 14, ( "Adamant", "Uncompromising; unyielding" ) )
        , ( 15, ( "Adjunct", "Something added, attached, or joined" ) )
        , ( 16, ( "Admonish", "To caution or reprimand" ) )
        , ( 17, ( "Adulterate", "To corrupt or make impure" ) )
        , ( 18, ( "Aesthetic", "Relating to beauty or art" ) )
        , ( 19, ( "Affected", "Pretentious, phony" ) )
        , ( 20, ( "Affinity", "Fondness; liking; similarity" ) )
        , ( 21, ( "Aggrandize", "To make larger or greater" ) )
        , ( 22, ( "Aggregate", "Amounting to a whole; total" ) )
        , ( 23, ( "Alacrity", "Cheerful willingness; eagerness; speed" ) )
        , ( 24, ( "Alchemy", "Medieval chemical philosophy based on chaning metal into gold; a seemingly magical power or process of transmutation" ) )
        , ( 25, ( "Allay", "To lessen; ease; soothe" ) )
        , ( 26, ( "Alleviate", "To relieve; improve partially" ) )
        , ( 27, ( "Alloy", "A combination; a mixture of two or more metals" ) )
        , ( 28, ( "Allure", "The power to entice by charm" ) )
        , ( 29, ( "Amalgamate", "To combine into a unified whole" ) )
        , ( 30, ( "Ambiguous", "Unclear or doubtful in meaning" ) )
        , ( 31, ( "Ambivalence", "The state of having conflicting emotional attitudes" ) )
        , ( 32, ( "Ambrosia", "Something delicious; the food of the gods" ) )
        , ( 33, ( "Ameliorate", "To improve" ) )
        , ( 34, ( "Amenable", "Agreeable; cooperative; suited" ) )
        , ( 35, ( "Amenity", "Something that increases comfort" ) )
        , ( 36, ( "Amulet", "Ornament worn as a charm against evil spirits" ) )
        , ( 37, ( "Anachronism", "Something out of the proper time" ) )
        , ( 38, ( "Analgesic", "Medication that reduces or eliminates pain" ) )
        , ( 39, ( "Analogous", "Comparable" ) )
        , ( 40, ( "Anarchy", "Absense of government; state of disorder" ) )
        , ( 41, ( "Anodyne", "Something that calms or soothes pain" ) )
        , ( 42, ( "Anomalous", "Irregular; deviating from the norm" ) )
        , ( 43, ( "Antecedent", "Something that comes before" ) )
        , ( 44, ( "Antediluvian", "Prehistoric" ) )
        , ( 45, ( "Antipathy", "Dislike; hostility" ) )
        , ( 46, ( "Apathy", "Indifference" ) )
        , ( 47, ( "Apex", "The highest point" ) )
        , ( 48, ( "Apogee", "The point in an orbit most distant from the body being orbited; the highest point" ) )
        , ( 49, ( "Apothegm", "A terse, witty saying" ) )
        , ( 50, ( "Appease", "To calm; pacify; placate" ) )
        , ( 51, ( "Appeallation", "Name" ) )
        , ( 52, ( "Apposite", "Strikingly appropriate and relevant" ) )
        , ( 53, ( "Apprise", "To inform" ) )
        , ( 54, ( "Approbation", "Praise; approval" ) )
        , ( 55, ( "Appropriate", "To take possession for one's own use; confiscate" ) )
        , ( 56, ( "Apropos", "Relevant" ) )
        , ( 57, ( "Arabesque", "Ornate design featuring intertwined curves; a ballet position in which one leg is extended in back while the other supports the weight of the body" ) )
        , ( 58, ( "Archeology", "The study of material evidence of past human life" ) )
        , ( 59, ( "Ardor", "Great emotion or passion" ) )
        , ( 60, ( "Ardous", "Extremely difficult; laborious" ) )
        , ( 61, ( "Argot", "A specialized vocabulary used by a group" ) )
        , ( 62, ( "Arrest", "To stop; to seize" ) )
        , ( 63, ( "Artifact", "Item made by human craft" ) )
        , ( 64, ( "Artless", "Guilesless; natural" ) )
        , ( 65, ( "Ascetic", "One who practices self-denial" ) )
        , ( 66, ( "Asperity", "Severity; harshness; irritability" ) )
        , ( 67, ( "Aspersion", "Slander; false rumor" ) )
        , ( 68, ( "Assiduous", "Diligent; hard-working" ) )
        , ( 69, ( "Assuage", "To make less severe" ) )
        , ( 70, ( "Astringent", "Harsh; severe" ) )
        , ( 71, ( "Asylum", "Place of refuge or shelter" ) )
        , ( 72, ( "Atavism", "Return of a trait after a period of absence" ) )
        , ( 73, ( "Attenuate", "To weaken" ) )
        , ( 74, ( "Audacious", "Bold; daring" ) )
        , ( 75, ( "Austere", "Stern; unadorned" ) )
        , ( 76, ( "Autonomous", "Self-governing; independent" ) )
        , ( 77, ( "Avarice", "Greed" ) )
        , ( 78, ( "Aver", "To affirm; declare to be true" ) )
        , ( 79, ( "Avocation", "Secondary occupation" ) )
        , ( 80, ( "Avuncular", "Like an uncle; benevolent and tolerant" ) )
        , ( 81, ( "Axiomatic", "Taken for granted" ) )
        , ( 82, ( "Bacchanalian", "Pertaining to riotous or drunken festivity; pertaining to revelry" ) )
        , ( 83, ( "Banal", "Commonplace; trite" ) )
        , ( 84, ( "Banter", "Playful conversation" ) )
        , ( 85, ( "Bard", "Poet" ) )
        , ( 86, ( "Bawdy", "Obscene" ) )
        , ( 87, ( "Beatify", "To sanctify; to bless; to ascribe virtue to" ) )
        , ( 88, ( "Bedizen", "To dress in a vulgar, showy manner" ) )
        , ( 89, ( "Behemoth", "Huge creature; anything very large and powerful" ) )
        , ( 90, ( "Belie", "To contradict; misinterpret; give a false impression" ) )
        , ( 91, ( "Beneficent", "Kindly; doing good" ) )
        , ( 92, ( "Bifurcate", "To divide into two parts" ) )
        , ( 93, ( "Blandishment", "Flattery" ) )
        , ( 94, ( "Blase", "Bored because of frequent indulgence; unconcerned" ) )
        , ( 95, ( "Bolster", "To give a boost to; prop up; support" ) )
        , ( 96, ( "Bombastic", "Pompous; using inflated language" ) )
        , ( 97, ( "Boorish", "Rude; insensitive" ) )
        , ( 98, ( "Bovine", "cowlike" ) )
        , ( 99, ( "Brazen", "Bold; shameless" ) )
        , ( 100, ( "Broach", "To mention for the first time" ) )
        , ( 101, ( "Bucolic", "Characteristic of the countryside; rustic; pastoral" ) )
        , ( 102, ( "Burgeon", "To flourish" ) )
        , ( 103, ( "Burnish", "To polish" ) )
        , ( 104, ( "Buttress", "To reinforce; support" ) )
        , ( 105, ( "Cacophonous", "Unpleasant or harsh-sounding" ) )
        , ( 106, ( "Cadge", "To beg; sponge" ) )
        , ( 107, ( "Callous", "Thick-skinned; insensitive" ) )
        , ( 108, ( "Calumny", "Flase and malicious accusation; slander" ) )
        , ( 109, ( "Canard", "False, deliberately misleading story" ) )
        , ( 110, ( "Canon", "An established principle; a basis or standard for judgement; a group of literary works" ) )
        , ( 111, ( "Cant", "Insincere talk; language of a particular group" ) )
        , ( 112, ( "Cantankerous", "Irritable; ill-humored" ) )
        , ( 113, ( "Capricious", "Fickle" ) )
        , ( 114, ( "Captious", "Faultfinding; intended to entrap, as in an argument" ) )
        , ( 115, ( "Cardinal", "Of foremost importance" ) )
        , ( 116, ( "Carnal", "Of the flesh or body; related to physical appetites" ) )
        , ( 117, ( "Carping", "To find fault; complain" ) )
        , ( 118, ( "Cartography", "Science of making maps" ) )
        , ( 119, ( "Caste", "Any of the hereditary social classes of Hindu society; social stratification" ) )
        , ( 120, ( "Castigation", "Punishment; chastisement; criticism" ) )
        , ( 121, ( "Cataclysm", "A violent upheaval that causes great destruction and change" ) )
        , ( 122, ( "Catalyst", "Something causing change" ) )
        , ( 123, ( "Categorical", "Absolute; without exception" ) )
        , ( 124, ( "Caucus", "Smaller group within an organization" ) )
        , ( 125, ( "Causal", "Involving a cause" ) )
        , ( 126, ( "Caustic", "Sarcastically biting; burning" ) )
        , ( 127, ( "Celestial", "Concerning the sky or heavens; sublime" ) )
        , ( 128, ( "Centrifugal", "Moving away from a center" ) )
        , ( 129, ( "Centripetal", "Moving or directed toward a center" ) )
        , ( 130, ( "Champion", "To defend or support" ) )
        , ( 131, ( "Chasten", "To correct by punishment or reproof; to restrain or subdue" ) )
        , ( 132, ( "Chicanery", "Trickery; fraud" ) )
        , ( 133, ( "Chivalry", "The qualities idealized by knighthood such as bravery and gallantry towards women" ) )
        , ( 134, ( "Churlish", "Rude; boorish" ) )
        , ( 135, ( "Circuitous", "Roundabout" ) )
        , ( 136, ( "Clairvoyant", "One who can predict the future; psychic" ) )
        , ( 137, ( "Clamor", "Noisy outcry" ) )
        , ( 138, ( "Clique", "A small, exclusive group" ) )
        , ( 139, ( "Cloister", "To confine; seclude" ) )
        , ( 140, ( "Coagulate", "Thicken; congeal" ) )
        , ( 141, ( "Coalesce", "To cause to become one" ) )
        , ( 142, ( "Coda", "A concluding part of a literary or musical composition; something that summarizes or concludes" ) )
        , ( 143, ( "Codify", "To sytematize" ) )
        , ( 144, ( "Cognizant", "Informed; conscious; aware" ) )
        , ( 145, ( "Collage", "Artistic composition of materials pasted over a surface; an assemblage of diverse elements" ) )
        , ( 146, ( "Commensurate", "Proportional" ) )
        , ( 147, ( "Compendium", "Brief, comprehensive summary" ) )
        , ( 148, ( "Complacent", "Self-satisfied" ) )
        , ( 149, ( "Complaisant", "Overly polite; willing to please; obliging" ) )
        , ( 150, ( "Complement", "Something that completes or makes up a whole" ) )
        , ( 151, ( "Compliant", "Yielding" ) )
        , ( 152, ( "Compunction", "Uneasiness caused by guilt" ) )
        , ( 153, ( "Concave", "Curving inward" ) )
        , ( 154, ( "Conciliatory", "Overcoming distrust or hostility" ) )
        , ( 155, ( "Concoct", "To invent" ) )
        , ( 156, ( "Concomitant", "Existing concurrently" ) )
        , ( 157, ( "Condone", "To overlook voluntarily; forgive" ) )
        , ( 158, ( "Confound", "To baffle; perplex; mix up" ) )
        , ( 159, ( "Congenial", "Similar in tastes and habits; friendly; suited to" ) )
        , ( 160, ( "Conjugal", "Pertaining to marriage agreement" ) )
        , ( 161, ( "Connoisseur", "A person possessing expert knowledge or training; a person of informed and discriminating taste" ) )
        , ( 162, ( "Conscript", "Person compulsorily enrolled for military service" ) )
        , ( 163, ( "Consecrate", "To declare sacred" ) )
        , ( 164, ( "Contend", "To assert" ) )
        , ( 165, ( "Contentious", "Quarrelsome; causing quarrels" ) )
        , ( 166, ( "Contiguous", "Touching; neighboring; connecting without a break" ) )
        , ( 167, ( "Continence", "Self-control; abstention from sexual activity" ) )
        , ( 168, ( "Contrite", "Very sorrowful for a wrong" ) )
        , ( 169, ( "Contumacious", "Disobedient; rebellious" ) )
        , ( 170, ( "Conundrum", "Riddle; puzzle with no solution" ) )
        , ( 171, ( "Convention", "Practice widely observed in a group; custom; accepted technique or device" ) )
        , ( 172, ( "Converge", "To approach; come together; tend to meet" ) )
        , ( 173, ( "Convex", "Curved outwards" ) )
        , ( 174, ( "Convivial", "Sociable" ) )
        , ( 175, ( "Convoluted", "Twisted; complicated" ) )
        , ( 176, ( "Copious", "Abundant; plentiful" ) )
        , ( 177, ( "Coquette", "Woman who flirts" ) )
        , ( 178, ( "Cornucopia", "Horn overflowing with fruit and grain; state of abundance" ) )
        , ( 179, ( "Cosmology", "Study of the universe as a totality; theory of the origin and structure of the universe" ) )
        , ( 180, ( "Covert", "Hidden; secret" ) )
        , ( 181, ( "Covetous", "Desiring something owned by another" ) )
        , ( 182, ( "Cozen", "To mislead by trick or fraud; deceive" ) )
        , ( 183, ( "Craven", "Cowardly" ) )
        , ( 184, ( "Credence", "Acceptance of something as true" ) )
        , ( 185, ( "Credo", "Statement of belief or principle; creed" ) )
        , ( 186, ( "Daunt", "To discourage; intimidate; dishearten" ) )
        , ( 187, ( "Dearth", "Scarcity" ) )
        , ( 188, ( "Debauchery", "Corruption" ) )
        , ( 189, ( "Decorum", "Proper behavior" ) )
        , ( 190, ( "Defame", "To malign; harm someone's reputation" ) )
        , ( 191, ( "Default", "To fail to act" ) )
        , ( 192, ( "Deference", "Respect; regard for another's wish" ) )
        , ( 193, ( "Defunct", "No longer existing" ) )
        , ( 194, ( "Delineate", "To represent or depict" ) )
        , ( 195, ( "Demographic", "Related to population balance" ) )
        , ( 196, ( "Demotic", "Pertaining to people" ) )
        , ( 197, ( "Demur", "To express doubt" ) )
        , ( 198, ( "Denigrate", "To slur someone's reputation" ) )
        , ( 199, ( "Denizen", "An inhabitant; a regular visitor" ) )
        , ( 200, ( "Denouement", "Outcome; unraveling of the plot of a play or work of literature" ) )
        , ( 201, ( "Deride", "To mock" ) )
        , ( 202, ( "Derivative", "Something derived; unoriginal" ) )
        , ( 203, ( "Desiccate", "To dry completely" ) )
        , ( 204, ( "Desuetude", "State of disuse" ) )
        , ( 205, ( "Desultory", "Random; disconnected; rambling" ) )
        , ( 206, ( "Deterrent", "Something that discourages or hinders" ) )
        , ( 207, ( "Detraction", "The act of taking away; derogatory comment on a person's character" ) )
        , ( 208, ( "Diaphanous", "Transparent; fine-textured; insubstantial; vague" ) )
        , ( 209, ( "Diatribe", "Bitter verbal attack" ) )
        , ( 210, ( "Dichotomy", "Division into two usually contradictory parts" ) )
        , ( 211, ( "Diffidence", "Shyness; lack of confidence" ) )
        , ( 212, ( "Diffuse", "To spread out" ) )
        , ( 213, ( "Digression", "Act of straying from the main point" ) )
        , ( 214, ( "Dirge", "Funeral Hymn" ) )
        , ( 215, ( "Disabuse", "To free from a misconception" ) )
        , ( 216, ( "Discerning", "Perceptive; exhibiting keen insight and good judgement" ) )
        , ( 217, ( "Discomfit", "To make uneasy; disconcert" ) )
        , ( 218, ( "Discordant", "Not in tune" ) )
        , ( 219, ( "Discredit", "To dishonor; disgrace; cause to be doubted" ) )
        , ( 220, ( "Discrepancy", "Difference between" ) )
        , ( 221, ( "Discrete", "Constituting a seperate thing; distinct" ) )
        , ( 222, ( "Discretion", "Quality of showing self-restraint in speech or actions; circumspection; freedom to act on one's own" ) )
        , ( 223, ( "Disingenuous", "Not candid; crafty" ) )
        , ( 224, ( "Disinterested", "Unprejudiced; objective" ) )
        , ( 225, ( "Disjointed", "Lacking order or coherence; dislocated" ) )
        , ( 226, ( "Dismiss", "Put away from consideration; reject" ) )
        , ( 227, ( "Disparage", "To belittle" ) )
        , ( 228, ( "Disparate", "Dissimilar" ) )
        , ( 229, ( "Dissemble", "To pretend; disguise one's motives" ) )
        , ( 230, ( "Disseminate", "To spread; scatter; disperse" ) )
        , ( 231, ( "Dissident", "Person who disagrees about beliefs, etc" ) )
        , ( 232, ( "Dissolution", "Disintegration; debauchery" ) )
        , ( 233, ( "Dissonance", "Discord; lack of harmony" ) )
        , ( 234, ( "Distend", "To expand; swell out" ) )
        , ( 235, ( "Distill", "Extract the essential elements" ) )
        , ( 236, ( "Distrait", "Inattentive; preoccupied" ) )
        , ( 237, ( "Diverge", "To vary; go in different directions from the same point" ) )
        , ( 238, ( "Divest", "To strip; deprive; rid" ) )
        , ( 239, ( "Divulge", "To make known something that is secret" ) )
        , ( 240, ( "Doctrinaire", "Relating to a person who cannot compromise about points of theory or doctrine; dogmatic; unyielding" ) )
        , ( 241, ( "Document", "To provide with written evidence to support" ) )
        , ( 242, ( "Doggerel", "Poor verse" ) )
        , ( 243, ( "Dogmatic", "Stating opinions without proof" ) )
        , ( 244, ( "Dormant", "Inactive" ) )
        , ( 245, ( "Dross", "Waste; worthless matter; trivial matter" ) )
        , ( 246, ( "Dupe", "To deceive; trick" ) )
        , ( 247, ( "Ebullient", "Exhilarated; enthusiastic" ) )
        , ( 248, ( "Eclectic", "Selecting from various sources" ) )
        , ( 249, ( "Effervesence", "State of high spirits or liveliness; the process of bubbling as gas escapes" ) )
        , ( 250, ( "Effete", "Depleted of vitality; overrefined; decadent" ) )
        , ( 251, ( "Efficacy", "Efficiency; effectiveness" ) )
        , ( 252, ( "Effrontery", "Shameless boldness; presumptuousness" ) )
        , ( 253, ( "Egoism", "The tendency to see things in relation to oneself; self-centeredness" ) )
        , ( 254, ( "Egotistical", "Excessively self-centered; conceited" ) )
        , ( 255, ( "Elegy", "A poem or song expressing lamentation" ) )
        , ( 256, ( "Elicit", "To provoke; draw out" ) )
        , ( 257, ( "Elixir", "A substance believed to have the power to cure ills" ) )
        , ( 258, ( "Elysian", "Blissful; delightful" ) )
        , ( 259, ( "Emaciated", "Thin and wasted" ) )
        , ( 260, ( "Embellish", "To adorn; decorate; enhance; make more attractive by adding details" ) )
        , ( 261, ( "Emollient", "Soothing; mollifying" ) )
        , ( 262, ( "Empirical", "Derived from observation or experiment" ) )
        , ( 263, ( "Emulate", "To imitate; copy" ) )
        , ( 264, ( "Encomium", "A formal expression of praise" ) )
        , ( 265, ( "Endemic", "Inherent; belonging to an area" ) )
        , ( 266, ( "Enervate", "To weaken" ) )
        , ( 267, ( "Engender", "To cuase; produce" ) )
        , ( 268, ( "Enhance", "To increase; improve" ) )
        , ( 269, ( "Entomology", "The scientific study of insects" ) )
        , ( 270, ( "Enunciate", "To pronounce clearly" ) )
        , ( 271, ( "Ephemeral", "Short-lived; fleeting" ) )
        , ( 272, ( "Epistemology", "Branch of philosophy that examines the nature of knowledge" ) )
        , ( 273, ( "Equable", "Steady; unvarying; serene" ) )
        , ( 274, ( "Equanimity", "Compsure; calmness" ) )
        , ( 275, ( "Equivocate", "To intentionally use vague language" ) )
        , ( 276, ( "Errant", "Mistaken; straying from the proper course" ) )
        , ( 277, ( "Erudite", "Learned; scholarly" ) )
        , ( 278, ( "Esoteric", "Hard to understand; known only to a few" ) )
        , ( 279, ( "Essay", "To make an attempt; subject to a test" ) )
        , ( 280, ( "Estimable", "Admirable; possible to estimate" ) )
        , ( 281, ( "Ethnocentric", "Based on the attitude that one's group is superior" ) )
        , ( 282, ( "Etiology", "Causes or origins" ) )
        , ( 283, ( "Etymology", "Origin and history of a word" ) )
        , ( 284, ( "Eugenics", "Study of factors that influence the hereditary qualities of the human race and ways to improve these qualities" ) )
        , ( 285, ( "Eulogy", "High praise, especially of a person who has recently died" ) )
        , ( 286, ( "Euphenism", "Use of agreeable or inoffensive language in place of unpleasant or offensive language" ) )
        , ( 287, ( "Euphoria", "A feeling of extreme happiness" ) )
        , ( 288, ( "Euthanasia", "Mercy killing" ) )
        , ( 289, ( "Evince", "To show plainly; be an indication of" ) )
        , ( 290, ( "Evocative", "Tending to call to mind or produce a reaction" ) )
        , ( 291, ( "Exacerbate", "To aggravate; make worse" ) )
        , ( 292, ( "Exact", "To force the payment of; demand and obtain by authority" ) )
        , ( 293, ( "Exculpate", "To clear of blame; vindicate" ) )
        , ( 294, ( "Execrable", "Detestable; abhorrent" ) )
        , ( 295, ( "Exhort", "To urge by strong appeals" ) )
        , ( 296, ( "Exigency", "Crisis; urgent requirements" ) )
        , ( 297, ( "Existential", "Having to do with existence; based on experience; having to do with the philosophy of existenialism" ) )
        , ( 298, ( "Exorcise", "To expel evil spirits; free from bad influences" ) )
        , ( 299, ( "Expatiate", "To speak or write at length" ) )
        , ( 300, ( "Expatriate", "To send into exile" ) )
        , ( 301, ( "Expiate", "To atone for" ) )
        , ( 302, ( "Explicate", "To explain; interpret; clarify" ) )
        , ( 303, ( "Expository", "Explanatory" ) )
        , ( 304, ( "Extant", "In existence; not lost" ) )
        , ( 305, ( "extemporaneous", "Unrehearsed" ) )
        , ( 306, ( "Extirpate", "To root up; to destroy" ) )
        , ( 307, ( "Extraneous", "Not essential" ) )
        , ( 308, ( "Extrapolation", "The act of estimation by projecting known information" ) )
        , ( 309, ( "Extrinsic", "Not inherent or essential" ) )
        , ( 310, ( "Facetious", "Humorous" ) )
        , ( 311, ( "Facilitate", "To make less difficult" ) )
        , ( 312, ( "Factotum", "A person who does all sorts of work; a handyman" ) )
        , ( 313, ( "Fallacious", "Based on a false idea or fact; misleading" ) )
        , ( 314, ( "Fallow", "Plowed but not sowed; uncultivated" ) )
        , ( 315, ( "Fatuous", "Foolishly self-satisfied" ) )
        , ( 316, ( "Fauna", "Animals of a period or region" ) )
        , ( 317, ( "Fawning", "Seeking favor by flattering" ) )
        , ( 318, ( "Felicitous", "Suitably expressed; appropriate; well chosen" ) )
        , ( 319, ( "Feral", "Existing in a wild or untamed state" ) )
        , ( 320, ( "Fervor", "Warmth and intensity of emotion" ) )
        , ( 321, ( "Fetid", "Having a bad smell" ) )
        , ( 322, ( "Fetter", "To bind; confine" ) )
        , ( 323, ( "Fiat", "Arbitrary order; authorization" ) )
        , ( 324, ( "Fidelity", "Loyalty; exact correspondence" ) )
        , ( 325, ( "Filibuster", "Use of obstructive tactics in a legislature to block passage of a law" ) )
        , ( 326, ( "Finesse", "To handle with a deceptive or evasive strategy; to use finesse, that is, refinement in performance" ) )
        , ( 327, ( "Fissure", "Crevice" ) )
        , ( 328, ( "Flag", "To droop; grow weak" ) )
        , ( 329, ( "Fledgling", "Beginner; novice" ) )
        , ( 330, ( "Flora", "Plants of a region or era" ) )
        , ( 331, ( "Florid", "Ruddy; reddish; flowery" ) )
        , ( 332, ( "Flourish", "An embellishment or ornamentation" ) )
        , ( 333, ( "Flout", "To treat scornfully" ) )
        , ( 334, ( "Flux", "Flowing; a continuous moving" ) )
        , ( 335, ( "Foment", "To incite; arouse" ) )
        , ( 336, ( "Forbearance", "Patience" ) )
        , ( 337, ( "Forestall", "To prevent; delay" ) )
        , ( 338, ( "Formidable", "Menacing; threatening" ) )
        , ( 339, ( "Forswear", "To renounce; repudiate" ) )
        , ( 340, ( "Founder", "To sink; fail; collapse" ) )
        , ( 341, ( "Fracas", "A loud quarrel; brawl" ) )
        , ( 342, ( "Fractious", "Quarrelsome; unruly; rebellious" ) )
        , ( 343, ( "Fresco", "A painting done on plaster" ) )
        , ( 344, ( "Frieze", "Ornamental band on a wall" ) )
        , ( 345, ( "Froward", "Stubbornly contrary; obstinately disobedient" ) )
        , ( 346, ( "Frugality", "Thrift" ) )
        , ( 347, ( "Fulminate", "To attack loudly; denounce" ) )
        , ( 348, ( "Fulsome", "So excessive as to be disgusting" ) )
        , ( 349, ( "Fusion", "Union; synthesis" ) )
        , ( 350, ( "Futile", "Ineffective; useless; fruitless" ) )
        , ( 351, ( "Gainsay", "To deny; dispute; oppose" ) )
        , ( 352, ( "Gambol", "To frolic; leap playfully" ) )
        , ( 353, ( "Garrulous", "Very talkative; wordy" ) )
        , ( 354, ( "Gauche", "Coarse and uncouth; clumsy" ) )
        , ( 355, ( "Geniality", "Cheerfulness; kindliness; sociability" ) )
        , ( 356, ( "Gerrymander", "To divide an area into voting districts in a way that favors a political party" ) )
        , ( 357, ( "Glib", "Fluent in an insincere way; offhand" ) )
        , ( 358, ( "goad", "To prod; urge on" ) )
        , ( 359, ( "Gossamer", "Sheer; light and delicate, like cobwebs" ) )
        , ( 360, ( "Gouge", "To tear out; scoop out; overcharge" ) )
        , ( 361, ( "Grandiloquent", "Pompous; bombastic" ) )
        , ( 362, ( "Gregarious", "Sociable" ) )
        , ( 363, ( "Grouse", "To complain" ) )
        , ( 364, ( "Guileless", "Free of cunning or deceit; artless" ) )
        , ( 365, ( "Guise", "Outward appearance; false appearance; pretense" ) )
        , ( 366, ( "Gullible", "Easily deceived" ) )
        , ( 367, ( "Gustatory", "Affecting the sense of taste" ) )
        , ( 368, ( "Halcyon", "Calm and peaceful; happy; golden; prosperous" ) )
        , ( 369, ( "Hallowed", "Holy; sacred" ) )
        , ( 370, ( "Harrangue", "Long, pompous speech; tirade" ) )
        , ( 371, ( "Harrowing", "Extremely distressing; terrifying" ) )
        , ( 372, ( "Herbivorous", "Relating to a herbivore, an animal that feeds mainly on plants" ) )
        , ( 373, ( "Hermetic", "Tightly sealed; magical" ) )
        , ( 374, ( "Heterodox", "Unorthodox; not widely accepted" ) )
        , ( 375, ( "Hieroglyphics", "A system of writing in which pictorial symbols represent meaning or sounds; writing or symbols that are difficult to decipher; the symbols used in advanced mathematics" ) )
        , ( 376, ( "Hirsute", "Covered with hair" ) )
        , ( 377, ( "Histrionic", "Relating to exaggerated emotional behavior calculated for effect; theatrical arts or performances" ) )
        , ( 378, ( "Homeostasis", "Automatic maintenance by an organsim of normal temperature, chemical balance, etc within itself" ) )
        , ( 379, ( "Homily", "Sermon; tedious moralizing lecture; platitude" ) )
        , ( 380, ( "Homogenous", "Composed of identical parts; uniform in composition" ) )
        , ( 381, ( "Hyperbole", "Purposeful exaggeration for effect" ) )
        , ( 382, ( "Iconoclastic", "Attacking cherished traditions" ) )
        , ( 383, ( "Ideological", "Relating to ideology, the set of ideas that form the basis of a political or economic system" ) )
        , ( 384, ( "Idolatry", "Idol worship; blind or excessive devotion" ) )
        , ( 385, ( "Igneous", "Produced by fire; volcanic" ) )
        , ( 386, ( "Imbroglio", "Complicated situation; an entanglement" ) )
        , ( 387, ( "Immutable", "Unchangeable" ) )
        , ( 388, ( "Impassive", "Showing no emotions" ) )
        , ( 389, ( "Impecunious", "Poor; having no money" ) )
        , ( 390, ( "Impede", "To hinder; block" ) )
        , ( 391, ( "Impermeable", "Impossible to penetrate" ) )
        , ( 392, ( "Imperturbable", "Not easily disturbed" ) )
        , ( 393, ( "Impervious", "Impossible to penetrate; incapable of being affected" ) )
        , ( 394, ( "Impinge", "To strike; encroach" ) )
        , ( 395, ( "Implacable", "Inflexible; incapable of being pleased" ) )
        , ( 396, ( "Implausible", "Unlikely; unbelievable" ) )
        , ( 397, ( "Implict", "Implied; understood but not stated" ) )
        , ( 398, ( "Implode", "Collapse inward violently" ) )
        , ( 399, ( "Imprecation", "Curse" ) )
        , ( 400, ( "Impute", "To relate a particular cause or source; attribute the fault to; assign as a characteristic" ) )
        , ( 401, ( "Inadvertently", "Carelessly; unintentionally" ) )
        , ( 402, ( "Incarnate", "Having bodily form" ) )
        , ( 403, ( "Inchoate", "Imperfectly formed or formulated" ) )
        , ( 404, ( "Incongruity", "State of not fitting" ) )
        , ( 405, ( "Inconsequential", "Insignificant; unimportant" ) )
        , ( 406, ( "Incorporate", "Introduce something into another thing already in existence; combine" ) )
        , ( 407, ( "Incursion", "Sudden invasion" ) )
        , ( 408, ( "Indeterminate", "Uncertain; indefinite" ) )
        , ( 409, ( "Indigence", "Poverty" ) )
        , ( 410, ( "Indolant", "Habitually lazy; idle" ) )
        , ( 411, ( "Ineluctable", "Not to be avoided or escaped; inevitable" ) )
        , ( 412, ( "Inert", "Unable to move; sluggish" ) )
        , ( 413, ( "Ingenuous", "Naive and trusting; lacking sophistication" ) )
        , ( 414, ( "Inherent", "Firmly established by nature or habit" ) )
        , ( 415, ( "Innocuous", "Harmless" ) )
        , ( 416, ( "Insensible", "Unconcious; unresponsive" ) )
        , ( 417, ( "Insinuate", "To suggest; say indirectly; imply" ) )
        , ( 418, ( "Insipid", "Lacking flavor; dull" ) )
        , ( 419, ( "Insouciant", "Indifferent; lacking concern or care" ) )
        , ( 420, ( "Insularity", "Narrow-mindedness; isolation" ) )
        , ( 421, ( "Insuperable", "Insurmountable; unconquerable" ) )
        , ( 422, ( "Intangible", "Not material" ) )
        , ( 423, ( "Interdict", "To forbid; prohibit; To confront and halt the activities, advance, or entry of" ) )
        , ( 424, ( "Internecine", "Deadly to both sides" ) )
        , ( 425, ( "Interpolate", "To insert; change by adding new words or material" ) )
        , ( 426, ( "Interregnum", "Interval between reigns; gap in continuity" ) )
        , ( 427, ( "Intimate", "Marked by close acquaintance" ) )
        , ( 428, ( "Intractable", "Not easily managed" ) )
        , ( 429, ( "Intransigence", "Stubbornness; refusal to compromise" ) )
        , ( 430, ( "Introspective", "Contemplating one's own thoughts and feelings" ) )
        , ( 431, ( "Inundate", "To cover with water; overwhelm" ) )
        , ( 432, ( "Inured", "Hardened; accustomed; used to" ) )
        , ( 433, ( "Invective", "Verbal abuse" ) )
        , ( 434, ( "Inveigh", "To disapprove; protest vehemently" ) )
        , ( 435, ( "Inveigle", "To win over by flattery or coaxing" ) )
        , ( 436, ( "Inveterate", "Confirmed; long-standing; deeply rooted" ) )
        , ( 437, ( "Invidious", "Likely to provike ill will; offensive" ) )
        , ( 438, ( "Irascible", "Easily angered" ) )
        , ( 439, ( "Irresolute", "Unsure of how to act; weak" ) )
        , ( 440, ( "Itinerant", "Wandering from place to place; unsettled" ) )
        , ( 441, ( "Itinerary", "Route of a traveler's journey" ) )
        , ( 442, ( "Jaundiced", "Having a yellowish discoloration of the skin; affected by envy, resentment, or hostility" ) )
        , ( 443, ( "Jibe", "To be in agreement" ) )
        , ( 444, ( "Jocose", "Fond of joking; jocular; playful" ) )
        , ( 445, ( "Juggernaut", "Huge force destorying everything in its path" ) )
        , ( 446, ( "Junta", "Group of people united in political intrigue" ) )
        , ( 447, ( "Juxtapose ", "Place side by side" ) )
        , ( 448, ( "Kudos", "Fame; glory; honor" ) )
        , ( 449, ( "Labile", "Likely to change" ) )
        , ( 450, ( "Laconic", "Using few words" ) )
        , ( 451, ( "Lambaste", "To thrash verbally or physically" ) )
        , ( 452, ( "Lascivious", "Lustful" ) )
        , ( 453, ( "Lassitude", "Lethargy; sluggishness" ) )
        , ( 454, ( "Latent", "Present but hidden; potential" ) )
        , ( 455, ( "Laud", "To praise" ) )
        , ( 456, ( "Lethargic", "Inactive" ) )
        , ( 457, ( "Levee", "An embankment that prevents a river from overflowing" ) )
        , ( 458, ( "Levity", "Light manner or attitude" ) )
        , ( 459, ( "Liberal", "Tolerant; broad-minded; generous; lavish" ) )
        , ( 460, ( "Libertine", "One without moral restraint" ) )
        , ( 461, ( "Libido", "Sexual desire" ) )
        , ( 462, ( "Lilliputian", "Extremely small" ) )
        , ( 463, ( "Limn", "To draw; describe" ) )
        , ( 464, ( "Limpid", "Clear; transparent" ) )
        , ( 465, ( "Lingusitic", "Pertaining to language" ) )
        , ( 466, ( "Litany", "Lengthy recitation; repetitive chant" ) )
        , ( 467, ( "Literati", "Scholarly or learned persons" ) )
        , ( 468, ( "Litigation", "Legal Proceedings" ) )
        , ( 469, ( "Log", "Record of a voyage; record of daily activities" ) )
        , ( 470, ( "Loquacious", "Talkative" ) )
        , ( 471, ( "Lucid", "Bright; clear; intelligible" ) )
        , ( 472, ( "Lucre", "Money or ptofits" ) )
        , ( 473, ( "Luminous", "Bright; brilliant; glowing" ) )
        , ( 474, ( "Lustrous", "Shining" ) )
        , ( 475, ( "Machiavellian", "Crafty; double-dealing" ) )
        , ( 476, ( "Machinations", "Plots or schemes" ) )
        , ( 477, ( "Maelstrom", "Whirlpool; turmoil" ) )
        , ( 478, ( "Magnanimity", "Generosity; nobility" ) )
        , ( 479, ( "Malign", "To speak evil of" ) )
        , ( 480, ( "Malinger", "To feign illness to escape duty" ) )
        , ( 481, ( "Malleable", "Capable of being shaped by pounding; impressionable" ) )
        , ( 482, ( "Maverick", "Dissenter" ) )
        , ( 483, ( "Megalomania", "Delusions of power or importance" ) )
        , ( 484, ( "Menagerie", "A variety of animals kept together" ) )
        , ( 485, ( "Mendacious", "Dishonest" ) )
        , ( 486, ( "Mendicant", "Beggar" ) )
        , ( 487, ( "Meretricious", "Gaudy; plausible but false; specious" ) )
        , ( 488, ( "Mesmerize", "To hypnotize" ) )
        , ( 489, ( "Metamorphosis", "Change; transform" ) )
        , ( 490, ( "Metaphysics", "Branch of philosophy that investigates the ultimate nature of reality" ) )
        , ( 491, ( "Meteoroligical", "Concerned with the weather" ) )
        , ( 492, ( "Meticulous", "Very careful; fastidious" ) )
        , ( 493, ( "Mettle", "Courage; endurance" ) )
        , ( 494, ( "Mettlesome", "Full of courage and fortitude; spirited" ) )
        , ( 495, ( "Microcosm", "A small system having analogies to a larger system; small world" ) )
        , ( 496, ( "Militate", "Work against" ) )
        , ( 497, ( "Minatory", "Threatening; menacing" ) )
        , ( 498, ( "Minuscule", "Very small" ) )
        , ( 499, ( "Minutia", "Petty details" ) )
        , ( 500, ( "Misanthrope", "One who hates humanity" ) )
        , ( 501, ( "Miscellany", "Mixture of writings on various subjects" ) )
        , ( 502, ( "Miscreant", "Villain; criminal" ) )
        , ( 503, ( "Misogynist", "One who hates women" ) )
        , ( 504, ( "Mitigate", "To cause to become less harsh, sever or painful; alleviate" ) )
        , ( 505, ( "Mnemonic", "Related to memory; assisting memory" ) )
        , ( 506, ( "Modicum", "Limited quantity" ) )
        , ( 507, ( "Mollify", "To smooth" ) )
        , ( 508, ( "Monolithic", "Solid and uniform; constituting a single, unified whole" ) )
        , ( 509, ( "Morose", "Ill-humored; sullen" ) )
        , ( 510, ( "Motley", "Many colored; made up of many parts" ) )
        , ( 511, ( "Multifarious", "Diverse" ) )
        , ( 512, ( "Mundane", "Worldly as opposed to spiritual; concerned with the ordinary" ) )
        , ( 513, ( "Necromancy", "Black magic" ) )
        , ( 514, ( "Negate", "To cancel out; nullify" ) )
        , ( 515, ( "Neologism", "New word or expression" ) )
        , ( 516, ( "Neophyte", "Novice; beginner" ) )
        , ( 517, ( "Nexus", "A means of connection; a connected group or series; a center" ) )
        , ( 518, ( "Nonplussed", "Bewildered" ) )
        , ( 519, ( "Nostalgia", "Sentimental longing for a past time" ) )
        , ( 520, ( "Nostrum", "Medicine or remedy of doubtful effectiveness; supposed cure" ) )
        , ( 521, ( "Nugatory", "Trifling; invalid" ) )
        , ( 522, ( "Obdurate", "Stubborn" ) )
        , ( 523, ( "Obsequious", "Overly submissive" ) )
        , ( 524, ( "Obsequy", "Funeral ceremony (often used in the plural, obsequies)" ) )
        , ( 525, ( "Obviate", "To make unnecessary; to anticipate and prevent" ) )
        , ( 526, ( "Occlude", "To shut; block" ) )
        , ( 527, ( "Occult", "Relating to practices connected with supernatural phenomena" ) )
        , ( 528, ( "Odyssey", "A long, adventrous voyage; a quest" ) )
        , ( 529, ( "Officious", "Too helpful; meddlesome" ) )
        , ( 530, ( "Olfactory", "Concerning the sense of smell" ) )
        , ( 531, ( "Oligarchy", "From of government in which power belongs to only a few leaders" ) )
        , ( 532, ( "Onerous", "Burdensome" ) )
        , ( 533, ( "Onomatopoeia", "Formation or use of words that imitate sounds of the actions they refer to" ) )
        , ( 534, ( "Opprobrium", "Disgrace; contempt" ) )
        , ( 535, ( "Ornithologist", "Scientist who studies birds" ) )
        , ( 536, ( "Oscillate", "To move back and forth" ) )
        , ( 537, ( "Ostentatious", "Showy; trying to attract attention; pretentious" ) )
        , ( 538, ( "Overweening", "Presumptuous; arrogant; overbearing" ) )
        , ( 539, ( "Paean", "Song of joy or triumph; a fervent expression of joy" ) )
        , ( 540, ( "Paleontology", "Study of past geological eras through fossil remains" ) )
        , ( 541, ( "Pallid", "Lacking color or liveliness" ) )
        , ( 542, ( "Panegyric", "Elaborate praise; formal hymn of praise" ) )
        , ( 543, ( "Paragon", "Model of excellence or perfection" ) )
        , ( 544, ( "Partisan", "One-sided; committed to a party, group, or cause; prejudiced" ) )
        , ( 545, ( "Pathological", "Departing from normal condition" ) )
        , ( 546, ( "Patois", "A regional dialect; nonstandard speech; jargon" ) )
        , ( 547, ( "Paucity", "Scarcity" ) )
        , ( 548, ( "Pedantic", "Showing off learning" ) )
        , ( 549, ( "Pellucid", "Transparent; translucent; easily understood" ) )
        , ( 550, ( "Penchant", "Inclination" ) )
        , ( 551, ( "Penury", "Extreme poverty" ) )
        , ( 552, ( "Peregrination", "A wandering from place to place" ) )
        , ( 553, ( "Peremptory", "Imperative; leaving no choice" ) )
        , ( 554, ( "Perennial", "Present throughout the years; persistent" ) )
        , ( 555, ( "Perfidious", "Faithless; disloyal; untrustworthy" ) )
        , ( 556, ( "Perfunctory", "Superficial; not thorough; performed really as a duty" ) )
        , ( 557, ( "Perigee", "Point in an orbit that is closest to the Earth" ) )
        , ( 558, ( "Permeable", "Penetrable" ) )
        , ( 559, ( "Perturb", "To disturb greatly; make uneasy or anxious; cause a body to deviate from its regular orbit" ) )
        , ( 560, ( "Pervasive", "Spread throughout every part" ) )
        , ( 561, ( "Petulant", "Rude; peevish" ) )
        , ( 562, ( "Phlegmatic", "Calm in temperment; sluggish" ) )
        , ( 563, ( "Phoenix", "Mythical, immortal bird that lives for 500 years, burns itself to death, and rises from its ashes; anything that is restored after suffering great destruction" ) )
        , ( 564, ( "Physiognomy", "Facial features" ) )
        , ( 565, ( "Piety", "Devoutness" ) )
        , ( 566, ( "Piquant", "Appealingly stimulating; pleasantly pungent; attractive" ) )
        , ( 567, ( "Pique", "Fleeting feeling of jurt pride" ) )
        , ( 568, ( "Placate", "To lessen another's anger; to pacify" ) )
        , ( 569, ( "Placid", "Calm" ) )
        , ( 570, ( "Plaintive", "Melancholy; mournful" ) )
        , ( 571, ( "Plasticity", "Condition of being able to be shaped or formed; pliability" ) )
        , ( 572, ( "Platitude", "Stal, overused expression" ) )
        , ( 573, ( "Platonic", "Spiritual; without sensual desire; theoretical" ) )
        , ( 574, ( "Plethora", "Excess; overabundance" ) )
        , ( 575, ( "Plumb", "To determine the depth; to examine deeply" ) )
        , ( 576, ( "Plummet", "To fall; plunge" ) )
        , ( 577, ( "Plutocracy", "Society ruled by the wealthy" ) )
        , ( 578, ( "Porous", "Full of holes; permeable to liquids" ) )
        , ( 579, ( "Poseur", "Person who affects an attitude or identity to impress others" ) )
        , ( 580, ( "Pragmatic", "Practical" ) )
        , ( 581, ( "Prate", "To talk idly; chatter" ) )
        , ( 582, ( "Prattle", "Meaningless, foolish talk" ) )
        , ( 583, ( "Preamble", "Preliminary statement" ) )
        , ( 584, ( "Precarious", "Uncertain" ) )
        , ( 585, ( "Precept", "Principle; law" ) )
        , ( 586, ( "Precipitate", "To cause to happen; throw down from a height OR rash; hasty; sudden" ) )
        , ( 587, ( "Place", "Holder" ) )
        , ( 588, ( "Precursor", "Forerunner; predecessor" ) )
        , ( 589, ( "Preempt", "To supersede; appropriate for oneself" ) )
        , ( 590, ( "Prehensile", "Capable of grasping" ) )
        , ( 591, ( "Premonition", "Forewarning; presentiment" ) )
        , ( 592, ( "Presage", "To foretell; indicate in advance" ) )
        , ( 593, ( "Presumptuous", "Rude; improperly bold; readiness to presume" ) )
        , ( 594, ( "Preternatural", "Beyond the normal course of nature; supernatural" ) )
        , ( 595, ( "Prevaricate", "To quibble; evade the truth" ) )
        , ( 596, ( "Primoridal", "Original; existing from the beginning" ) )
        , ( 597, ( "Pristine", "Untouched; uncorrupted" ) )
        , ( 598, ( "Probity", "Honesty; high-mindedness" ) )
        , ( 599, ( "Problematic", "Posing a problem; doubtful; unsettled" ) )
        , ( 600, ( "Prodigal", "Wasteful; extravagant; lavish" ) )
        , ( 601, ( "Profound", "Deep; not superficial" ) )
        , ( 602, ( "Prohibitive", "So high as to prevent the purchase or use of; preventing; forbidding" ) )
        , ( 603, ( "Proliferate", "To increase rapidly" ) )
        , ( 604, ( "Propensity", "Inclination; tendency" ) )
        , ( 605, ( "Propitiate", "To win over; appease" ) )
        , ( 606, ( "Propriety", "Correct conduct; fitness" ) )
        , ( 607, ( "Proscribe", "To condemn; forbid; outlaw" ) )
        , ( 608, ( "Provident", "Providing for future needs; frugal" ) )
        , ( 609, ( "Puissant", "Powerful" ) )
        , ( 610, ( "Punctilious", "Careful in observing rules of behavior or ceremony" ) )
        , ( 611, ( "Pungent", "Strong or sharp in smell or taste; penetrating; caustic; to the point" ) )
        , ( 612, ( "Purport", "To profess; suppose; claim" ) )
        , ( 613, ( "Pusillanimous", "Cowardly" ) )
        , ( 614, ( "Quagmire", "Marsh; difficult situation" ) )
        , ( 615, ( "Quail", "To cower; lose heart" ) )
        , ( 616, ( "Qualified", "Limited; restricted" ) )
        , ( 617, ( "Qualm", "Sudden feeling of faintness or nausea; uneasy feeling about the rightness of actions" ) )
        , ( 618, ( "Query", "To question" ) )
        , ( 619, ( "Quibble", "To argue over insignificant and irrelevant details" ) )
        , ( 620, ( "Quiescent", "Inactive; still" ) )
        , ( 621, ( "Quorum", "Number of members necessary to conduct a meeting" ) )
        , ( 622, ( "Raconteur", "Witty, skillful storyteller" ) )
        , ( 623, ( "Rail", "To scold with bitter or abusive language" ) )
        , ( 624, ( "Raiment", "Clothing" ) )
        , ( 625, ( "Ramification", "Implication; outgrowth; consequence" ) )
        , ( 626, ( "Rarefied", "Refined" ) )
        , ( 627, ( "Rationale", "Fundamental reason" ) )
        , ( 628, ( "Rebus", "Puzzle in which pictures or symbols represent words" ) )
        , ( 629, ( "Recalcitrant", "Resisting authority or control" ) )
        , ( 630, ( "Recant", "To retract a statement or opinion" ) )
        , ( 631, ( "Recluse", "A person who lives in seclusion and often in solitude" ) )
        , ( 632, ( "Recondite", "Abstruse; profound" ) )
        , ( 633, ( "Redoubtable", "Formidable; arousing fear; worthy of respect" ) )
        , ( 634, ( "Refractory", "Stubborn; unmanageable; resisting ordinary methods of treatment" ) )
        , ( 635, ( "Refulgent", "Brightly shining; resplendent" ) )
        , ( 636, ( "Refute", "To contradict; disprove" ) )
        , ( 637, ( "Regale", "To entertain" ) )
        , ( 638, ( "Relegate", "To consign to an inferior position" ) )
        , ( 639, ( "Remonstrate", "To object or protest" ) )
        , ( 640, ( "Renege", "To go back on one's word" ) )
        , ( 641, ( "Reparation", "Amends; compensation" ) )
        , ( 642, ( "Repine", "Fret; complain" ) )
        , ( 643, ( "Reprise", "Repetition, especially of a piece of music" ) )
        , ( 644, ( "Reproach", "To find fault with; blame" ) )
        , ( 645, ( "Reprobate", "Morally unprincipled person" ) )
        , ( 646, ( "Repudiate", "To reject as having no authority" ) )
        , ( 647, ( "Rescind", "To cancel" ) )
        , ( 648, ( "Resolution", "Determination; resolve" ) )
        , ( 649, ( "Resolve", "Determination; firmness of purpse" ) )
        , ( 650, ( "Reticent", "Not speaking freely; reserved; reluctant" ) )
        , ( 651, ( "Reverent", "Expressing deep respect; worshipful" ) )
        , ( 652, ( "Riposte", "A retaliatory action or retort" ) )
        , ( 653, ( "Rococo", "Excessively ornate; highly decorated; style of architecture in 18th-century Europe" ) )
        , ( 654, ( "Rubric", "Tile or heading; category; established mode of procedure or conduct; protocol" ) )
        , ( 655, ( "Rue", "To regret" ) )
        , ( 656, ( "Ruse", "Trick; crafty stratagem; subterfuge" ) )
        , ( 657, ( "Sage", "Wise" ) )
        , ( 658, ( "Salacious", "Lascivious; lustful" ) )
        , ( 659, ( "Salubrious", "Healthful" ) )
        , ( 660, ( "Salutary", "Expecting improvement; favorable to health" ) )
        , ( 661, ( "Sanction", "To approve; ratify; permit" ) )
        , ( 662, ( "Sardonic", "Cynical; scornfully mocking" ) )
        , ( 663, ( "Sartorial", "Pertaining to tailors" ) )
        , ( 664, ( "Satiate", "To satisfy" ) )
        , ( 665, ( "Saturate", "To soak throughly; imbue throughout" ) )
        , ( 666, ( "Saturnine", "Gloomy" ) )
        , ( 667, ( "Satyr", "A creature that is half-man, half-beast with the horns and legs of a goat; it is a follower of Dionysos; a lecher" ) )
        , ( 668, ( "Savor", "To enjoy; have a distinctive flavor or smell" ) )
        , ( 669, ( "Schematic", "Relating to or in the form of an outline or diagram" ) )
        , ( 670, ( "Secrete", "Produce and release substance into organism" ) )
        , ( 671, ( "Sedition", "Behavior prompting rebellion" ) )
        , ( 672, ( "Sedulous", "Diligent" ) )
        , ( 673, ( "Seismic", "Relating to earthquakes; earthshaking" ) )
        , ( 674, ( "Sensual", "Relating to the senses; gratifying the physical senses, especially sexual appetites" ) )
        , ( 675, ( "Sensuous", "Relating to the senses; operating through the senses" ) )
        , ( 676, ( "Sentient", "Aware; concious; able to perceive" ) )
        , ( 677, ( "Servile", "Submissive; obedient" ) )
        , ( 678, ( "Sextant", "Navigation tool that determines latitude and longitude" ) )
        , ( 679, ( "Shard", "A piece of broken glass or pottery" ) )
        , ( 680, ( "Sidereal", "Relating to the stars" ) )
        , ( 681, ( "Simian", "Apelike; relating to apes" ) )
        , ( 682, ( "Simile", "Comparison of one thing with abother using \"like\" or \"as\"" ) )
        , ( 683, ( "Sinecure", "Well-paying job or office that requires little or no work" ) )
        , ( 684, ( "Singular", "Unique; extraordinary; odd" ) )
        , ( 685, ( "Sinuous", "Winding; intricate; complex" ) )
        , ( 686, ( "Skeptic", "One who doubts" ) )
        , ( 687, ( "Sobriety", "Seriousness" ) )
        , ( 688, ( "Sodden", "Thoroughly soaked; saturated" ) )
        , ( 689, ( "Solicitous", "Concerned; attentive; eager" ) )
        , ( 690, ( "Soliloquy", "Long speech given to oneself" ) )
        , ( 691, ( "Solvent", "Able to meet financial obligations" ) )
        , ( 692, ( "Somatic", "Relating to or affecting the body; corporeal" ) )
        , ( 693, ( "Soporific", "Sleeo producing" ) )
        , ( 694, ( "Sordid", "Filthy; contemptible and corrupt" ) )
        , ( 695, ( "Specious", "Seeming to be logical and sound, but not really so" ) )
        , ( 696, ( "Spectrum", "Band of colors produced when sunlight passes through a prism; a broad range of related ideas or objects" ) )
        , ( 697, ( "Spendthrift", "Person who spends money recklessly" ) )
        , ( 698, ( "Sporadic", "Irregular" ) )
        , ( 699, ( "Squalor", "Filthy, wretched condition" ) )
        , ( 700, ( "Staccato", "Marked by abrupt, clear-cut sounds" ) )
        , ( 701, ( "Stanch", "To stop or check the flow of" ) )
        , ( 702, ( "Stentorian", "Extremely loud" ) )
        , ( 703, ( "Stigma", "Mark of disgrace or inferiority" ) )
        , ( 704, ( "Stint", "To be sparing" ) )
        , ( 705, ( "Stipulate", "To specify an essential condition" ) )
        , ( 706, ( "Stolid", "Having or showing little emotion" ) )
        , ( 707, ( "Stratified", "Arranged in layers" ) )
        , ( 708, ( "Striated", "Marked with thin, narrow grooves or channes" ) )
        , ( 709, ( "Stricture", "Something that restrains; negative criticism" ) )
        , ( 710, ( "Strident", "Loud; harsh; unpleasantly noisy" ) )
        , ( 711, ( "Strut", "To swagger; display to impress others" ) )
        , ( 712, ( "Stultify", "To impair or reduce to uselessness" ) )
        , ( 713, ( "Stupefy", "To dull the senses of; stun; astonish" ) )
        , ( 714, ( "Stygian", "Dark and gloomy; hellish" ) )
        , ( 715, ( "Subpoena", "Notice ordering someone to appear in court" ) )
        , ( 716, ( "Subside", "To settle down; grow quiet" ) )
        , ( 717, ( "Substantiate", "To support with proof or evidence" ) )
        , ( 718, ( "Substantive", "Essential; pertaining to the substance" ) )
        , ( 719, ( "Subsume", "To include; incorporate" ) )
        , ( 720, ( "Subversive", "Intended to undermine or overthrow, especially an established government" ) )
        , ( 721, ( "Succor", "Relief; help in time of distress or want" ) )
        , ( 722, ( "Suffrage", "The right to vote" ) )
        , ( 723, ( "Sundry", "Various" ) )
        , ( 724, ( "Supersede", "To replace, especially to displace as inferior or antiquated" ) )
        , ( 725, ( "Supine", "Lying on the back; marked by lethargy" ) )
        , ( 726, ( "Supplant", "To replace; substitute" ) )
        , ( 727, ( "Suppliant", "Beseeching" ) )
        , ( 728, ( "Supplicant", "One who asks humbly and earnestly" ) )
        , ( 729, ( "Supposition", "The act of assuming to be true or real" ) )
        , ( 730, ( "Syllogism", "A form of deductive reasoning that has a major premise, a minor premise, and a conclusion" ) )
        , ( 731, ( "Sylvan", "Related to the woods or forest" ) )
        , ( 732, ( "Tacit", "Silently understood; implied" ) )
        , ( 733, ( "Taciturn", "Habitually untalkative" ) )
        , ( 734, ( "Talisman", "Charm to bring good luck and avert misfortune" ) )
        , ( 735, ( "Tangential", "Peripheral; digressing" ) )
        , ( 736, ( "Tautology", "Unnecessary repetition" ) )
        , ( 737, ( "Taxonomy", "Science of classification; in biology, the process of classifying organisms in categories" ) )
        , ( 738, ( "Tenet", "Belief; doctrine" ) )
        , ( 739, ( "Tenuous", "Weak; insubstantial" ) )
        , ( 740, ( "Theocracy", "Government by priests representing a god" ) )
        , ( 741, ( "Thespian", "An actor or actress" ) )
        , ( 742, ( "Timbre", "The characteristic quality of sound produced by a particular instrument or voice; tone color" ) )
        , ( 743, ( "Tirade", "Long, violent speech; verbal assault" ) )
        , ( 744, ( "Toady", "Flatterer; hanger-on; yes-man" ) )
        , ( 745, ( "Tome", "Book, usually large and academic" ) )
        , ( 746, ( "Torpor", "Lethargy; dormancy; sluggishness" ) )
        , ( 747, ( "Torque", "A turning or twisting force; the moment of a force" ) )
        , ( 748, ( "Tortuous", "Having many twists and turns; highly complex" ) )
        , ( 749, ( "Tout", "To promote or praise energetically" ) )
        , ( 750, ( "Tractable", "Obedient; yielding" ) )
        , ( 751, ( "Transgression", "Act of trespassing or violating a law or rule" ) )
        , ( 752, ( "Transient", "Temporary; short-lived; fleeting" ) )
        , ( 753, ( "Translucent", "Partially transparent" ) )
        , ( 754, ( "Travail", "Work, especially arduous work; tribulation; anguish" ) )
        , ( 755, ( "Travesty", "Parody; exaggerated imitation; caricature" ) )
        , ( 756, ( "Treatise", "Article treating a subject systematically and thoroughly" ) )
        , ( 757, ( "Tremulous", "Trembling; quivering; frugal; timid" ) )
        , ( 758, ( "Trepidation", "Fear and anxiety" ) )
        , ( 759, ( "Truculence", "Aggressiveness; ferocity" ) )
        , ( 760, ( "Tryst", "Agreement between lovers to meet; rendezvous" ) )
        , ( 761, ( "Tumid", "Swollen; distended" ) )
        , ( 762, ( "Turbid", "Muddy; opaque; in a state of great confusion" ) )
        , ( 763, ( "Turgid", "Swollen; bloated; pompous" ) )
        , ( 764, ( "Tutelary", "Serving as a guardian or protector" ) )
        , ( 765, ( "Uncanny", "Mysterious; strange" ) )
        , ( 766, ( "Undulating", "Moving in waves" ) )
        , ( 767, ( "Unfeigned", "Not false; not made up; genuine" ) )
        , ( 768, ( "Untenable", "Indefensible" ) )
        , ( 769, ( "Untoward", "Not favorable; troublesome; adverse; unruly" ) )
        , ( 770, ( "Usury", "Practice of lending money at exorbitant rates" ) )
        , ( 771, ( "Vacillate", "To waver; oscillate" ) )
        , ( 772, ( "Vacuous", "Empty; void; lacking intelligence; purposeless" ) )
        , ( 773, ( "Valedictory", "Pertaining to a farewell" ) )
        , ( 774, ( "Vapid", "Tasteless; dull" ) )
        , ( 775, ( "Variegated", "Varied; marked with different colors" ) )
        , ( 776, ( "Vaunt", "To boast; brag" ) )
        , ( 777, ( "Venal", "Bribable; mercenary; corruptible" ) )
        , ( 778, ( "Vendetta", "Prolonged feud marked by bitter hostility" ) )
        , ( 779, ( "Venerate", "To adore; honor; respect" ) )
        , ( 780, ( "Veracious", "Truthful; accurate" ) )
        , ( 781, ( "Verbose", "Wordy" ) )
        , ( 782, ( "Vertigo", "Dizziness" ) )
        , ( 783, ( "Vexation", "Irritation; annoyance; confusion; puzzlement" ) )
        , ( 784, ( "Viable", "Practicable; capable of developing" ) )
        , ( 785, ( "Vindictive", "Spiteful; vengeful; unforgibing" ) )
        , ( 786, ( "Virtuoso", "Someone with masterly skills; expert musician" ) )
        , ( 787, ( "Visage", "Countenance; appearance; aspect" ) )
        , ( 788, ( "Viscous", "Thick; syrupy and sticky" ) )
        , ( 789, ( "Vititate", "To impair the quality of; corrupt morally; make inoperative" ) )
        , ( 790, ( "Vituperative", "Using or containing harsh, abusive censure" ) )
        , ( 791, ( "Vivisection", "dissection, surgery, or painful experiments performed on a living animal for the purpose of scientific research" ) )
        , ( 792, ( "Vogue", "Prevailing fashion or practice" ) )
        , ( 793, ( "Volatile", "Tending to vary frequently; fickle" ) )
        , ( 794, ( "Vortex", "Whirlpool; whirlwind; center of turbulence" ) )
        , ( 795, ( "Warranted", "Justified" ) )
        , ( 796, ( "Wary", "Careful; cautious" ) )
        , ( 797, ( "Welter", "To wallow or roll; toss about; be in turmoil" ) )
        , ( 798, ( "Whimsical", "Fanciful; unpredictable" ) )
        , ( 799, ( "Wistful", "Vaguely longing; sadly thoughtful" ) )
        , ( 800, ( "Zealot", "One who is fanatically devoted to a cause" ) )
        ]
